[package]
name = "taeto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.2"
fixed = "1.15.0"
sfml = "0.16.0"
#signal-hook = "0.3.14"
termios = "0.3.3"
term_size = "0.3.2"
